name: Docker Image CI

on:
  push:
    branches: [ "github_pipeline" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: gradlew build
      run: ./gradlew :app:distTar

    - name: extract build tar
      run: tar -xvf app.tar
      shell: bash

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lsfohtmbm-web:$(date +%s)
