name: Docker Image CI

on:
  push:
    branches: [ "github_pipeline" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Create distribution tar archive
      run: ./gradlew :app:distTar

    - name: Extract distribution files
      run: tar -xvf ./app/build/distributions/app.tar -C ./app/build/distributions
      shell: bash

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lsfohtmbm-web:$(date +%s)
