name: Docker Image CI

on:
  push:
    branches: [ "github_pipeline" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: gradlew build
      run: ./gradlew build

#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
